language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t machinedatainsights/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true machinedatainsights/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-621035315092"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
